### ISSUE TITLE
error parsing VCF query file

### ISSUE THREAD

**Issue by brainstorm** [brentp/irelate#2]
Hello Brent!

While working with [PCGR](https://github.com/sigven/pcgr) we found the following issue when parsing this particular INFO field in a VCF file:

> vcfanno.go:132: error parsing VCF query file /workdir/output/test.pcgr_ready.pcgr_vep.vcf.gz: INFO error: ##INFO=<ID=ACGTNacgtnMINUS,Number=10,Type=Integer,Description="The first five numbers correspond to the number of bases on forward reads found to be A, C, G, T, or N, while the last five numbers correspond to bases on reverse reads found to be a, c, g, t, or n on minus stranded PCR templates (only reads with a mapping quality greater or equal to 30, and bases with a base quality greater or equal to 13 were considered).">, []. [line: 132]

> INFO error: ##INFO=<ID=ACGTNacgtnPLUS,Number=10,Type=Integer,Description="The first five numbers correspond to the number of bases on forward reads found to be A, C, G, T, or N, while the last five numbers correspond to bases on reverse reads found to be a, c, g, t, or n on plus stranded PCR templates (only reads with a mapping quality greater or equal to 30, and bases with a base quality greater or equal to 13 were considered).">, []. [line: 133]

Can you spot what's off? I'm not sure what's wrong with it other than perhaps multiline, excessive length, or...?

cc @ohofmann @chapmanb

**Comment by brentp** [comment]
not sure. can you paste a small vcf that contains this header?

**Comment by brainstorm** [comment]
Sure, here's the file in question (zipped because github upload limitations and just the header): [test.vcf.zip](https://github.com/brentp/irelate/files/1317913/test.vcf.zip)

**Comment by brentp** [comment]
what version of vcfanno are you using? this works fine in current version.
I think in the past, I was expecting Number to have only a single digit (so 10 would have failed) but now it should work fine.

**Comment by brainstorm** [comment]
It seems that PCGR's vcfanno version is quite a [few releases behind (pulls in vcfanno 0.0.11 in the Dockerfile)](https://github.com/sigven/pcgr/blob/master/src/Dockerfile#L80).

@sigven, do you mind bumping vcfanno's version up in that Dockerfile and its accompanying container on the dockerhub?

**Comment by sigven** [comment]
I am on it, new release on its way.

**Comment by brainstorm** [comment]
Awesome! Thanks Sigve and Brent, closing this issue then ;)
