### ISSUE TITLE
Collection of related objects from a single source

### ISSUE THREAD

**Issue by bsipos** [brentp/irelate#3]
Hello,

I would like to create a collection of related objects from a single source using IRelate.
A simple concrete example would be creating a collection of sets of features which have exactly same start and end from a single GFF file. 
I imagine that in contrast with existing IRelate functionality this would require comparing relatables from the same source to each other.

Thanks,
Botond

**Comment by brentp** [comment]
I have just pushed a change for this. When using `IRelate` it would look like:

```
IRelate(CheckRelatedByOverlap, SelfRelations, Less, mystream) 
```

where `SelfRelations` is a constant that allows self relations. Let me know if this addresses your use-case.

**Comment by bsipos** [comment]
Thanks! I cannot find the commit though. Did you push it on a branch?

**Comment by brentp** [comment]
:| pushed it now.

**Comment by bsipos** [comment]
Pulled it and invoked as instructed. But I get back EOF from IRelate right away. :(

**Comment by brentp** [comment]
ok. now it's actually supported in latest commet. Here's an example:

```Go
package main

import (
	"fmt"
	"io"
	"log"

	"github.com/brentp/irelate"
	"github.com/brentp/irelate/interfaces"
)

func check(e error) {
	if e != nil {
		log.Fatal(e)
	}
}

type ri struct {
	i               int
	interval_starts []int
}

type interval struct {
	start   int
	related []interfaces.Relatable
}

func (r *ri) Next() (interfaces.Relatable, error) {
	if r.i == len(r.interval_starts) {
		return nil, io.EOF
	}
	result := &interval{start: r.interval_starts[r.i]}
	r.i++
	return result, nil
}

func (r *ri) Close() error {
	return nil
}

func (i *interval) Chrom() string {
	return "chr1"
}
func (i *interval) Start() uint32 {
	return uint32(i.start)
}
func (i *interval) End() uint32 {
	return uint32(i.start + 20)
}

func (i *interval) Related() []interfaces.Relatable {
	return i.related
}

func (i *interval) AddRelated(r interfaces.Relatable) {
	i.related = append(i.related, r)
}

func (i *interval) Source() uint32 {
	return 0
}
func (i *interval) SetSource(u uint32) {
}

func main() {
	rels := &ri{i: 0, interval_starts: []int{0, 5, 10, 15, 20, 25, 110, 115}}

	it := irelate.IRelate(irelate.CheckRelatedByOverlap, irelate.SelfRelations, irelate.Less, rels)
	for {
		interval, err := it.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			panic(err)
		}
		fmt.Printf("%s\t%d\t%d\t%d\n", interval.Chrom(), interval.Start(), interval.End(), len(interval.Related()))
	}
}
```

**Comment by bsipos** [comment]
Thanks a lot! Now this almost does what I want. However, the current code gives back each relatable from the iterator with the Realted() slot filled with all other related features. 
What I really want is "clusters" of related objects with no duplication (so each relatable appears only once in a cluster with all the other pairwisely related features). 
I realise this might not be easy to achieve with IRelate (which would be nice), in which case I will have to roll my own code.
